AddCSLuaFile()

setfenv( 1, DOOM )

EnumStart("GameMode_t")
EnumAdd("shareware")
EnumAdd("registered")
EnumAdd("commercial")
EnumAdd("retail")
EnumAdd("indetermined")

EnumStart()
EnumAdd("ML_LABEL")
EnumAdd("ML_THINGS")
EnumAdd("ML_LINEDEFS")
EnumAdd("ML_SIDEDEFS")
EnumAdd("ML_VERTEXES")
EnumAdd("ML_SEGS")
EnumAdd("ML_SSECTORS")
EnumAdd("ML_NODES")
EnumAdd("ML_SECTORS")
EnumAdd("ML_REJECT")
EnumAdd("ML_BLOCKMAP")

EnumStart("result_e")
EnumAdd("ok")
EnumAdd("crushed")
EnumAdd("pastdest")

EnumStart("floor_e")
EnumAdd("lowerFloor")
EnumAdd("lowerFloorToLowest")
EnumAdd("turboLower")
EnumAdd("raiseFloor")
EnumAdd("raiseFloorToNearest")
EnumAdd("raiseToTexture")
EnumAdd("lowerAndChange")
EnumAdd("raiseFloor24")
EnumAdd("raiseFloor24AndChange")
EnumAdd("raiseFloorCrush")
EnumAdd("raiseFloorTurbo")
EnumAdd("donutRaise")
EnumAdd("raiseFloor512")

EnumStart("stair_e")
EnumAdd("build8")
EnumAdd("turbo16")

EnumStart("vldoor_e")
EnumAdd("normal")
EnumAdd("close30ThenOpen")
EnumAdd("close")
EnumAdd("open")
EnumAdd("raiseIn5Mins")
EnumAdd("blazeRaise")
EnumAdd("blazeOpen")
EnumAdd("blazeClose")

EnumStart("ceiling_e")
EnumAdd("lowerToFloor")
EnumAdd("raiseToHighest")
EnumAdd("lowerAndCrush")
EnumAdd("crushAndRaise")
EnumAdd("fastCrushAndRaise")
EnumAdd("silentCrushAndRaise")

EnumStart("plat_e")
EnumAdd("up")
EnumAdd("down")
EnumAdd("waiting")
EnumAdd("in_stasis")

EnumStart("plattype_e")
EnumAdd("perpetualRaise")
EnumAdd("downWaitUpStay")
EnumAdd("raiseAndChange")
EnumAdd("raiseToNearestAndChange")
EnumAdd("blazeDWUS")
